<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 1 Review of Multiple Linear Regression | Stat 455: Advanced Statistical Modeling Notes</title>
  <meta name="description" content="Chapter 1 Review of Multiple Linear Regression | Stat 455: Advanced Statistical Modeling Notes" />
  <meta name="generator" content="bookdown 0.23 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 1 Review of Multiple Linear Regression | Stat 455: Advanced Statistical Modeling Notes" />
  <meta property="og:type" content="book" />
  
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 1 Review of Multiple Linear Regression | Stat 455: Advanced Statistical Modeling Notes" />
  
  
  



<meta name="date" content="2022-01-07" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="index.html"/>
<link rel="next" href="introduction-to-correlated-data.html"/>
<script src="libs/jquery-3.5.1/jquery-3.5.1.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>


<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
code > span.kw { color: #007020; font-weight: bold; } /* Keyword */
code > span.dt { color: #902000; } /* DataType */
code > span.dv { color: #40a070; } /* DecVal */
code > span.bn { color: #40a070; } /* BaseN */
code > span.fl { color: #40a070; } /* Float */
code > span.ch { color: #4070a0; } /* Char */
code > span.st { color: #4070a0; } /* String */
code > span.co { color: #60a0b0; font-style: italic; } /* Comment */
code > span.ot { color: #007020; } /* Other */
code > span.al { color: #ff0000; font-weight: bold; } /* Alert */
code > span.fu { color: #06287e; } /* Function */
code > span.er { color: #ff0000; font-weight: bold; } /* Error */
code > span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #880000; } /* Constant */
code > span.sc { color: #4070a0; } /* SpecialChar */
code > span.vs { color: #4070a0; } /* VerbatimString */
code > span.ss { color: #bb6688; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #19177c; } /* Variable */
code > span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code > span.op { color: #666666; } /* Operator */
code > span.bu { } /* BuiltIn */
code > span.ex { } /* Extension */
code > span.pp { color: #bc7a00; } /* Preprocessor */
code > span.at { color: #7d9029; } /* Attribute */
code > span.do { color: #ba2121; font-style: italic; } /* Documentation */
code > span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
</style>


<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Stat 455 Notes</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a></li>
<li class="chapter" data-level="1" data-path="review-of-multiple-linear-regression.html"><a href="review-of-multiple-linear-regression.html"><i class="fa fa-check"></i><b>1</b> Review of Multiple Linear Regression</a><ul>
<li class="chapter" data-level="1.1" data-path="review-of-multiple-linear-regression.html"><a href="review-of-multiple-linear-regression.html#exploratory-data-analysis"><i class="fa fa-check"></i><b>1.1</b> Exploratory Data Analysis</a><ul>
<li class="chapter" data-level="1.1.1" data-path="review-of-multiple-linear-regression.html"><a href="review-of-multiple-linear-regression.html#kentucky-derby-data"><i class="fa fa-check"></i><b>1.1.1</b> Kentucky Derby Data</a></li>
<li class="chapter" data-level="1.1.2" data-path="review-of-multiple-linear-regression.html"><a href="review-of-multiple-linear-regression.html#some-data-wrangling"><i class="fa fa-check"></i><b>1.1.2</b> Some Data Wrangling</a></li>
<li class="chapter" data-level="1.1.3" data-path="review-of-multiple-linear-regression.html"><a href="review-of-multiple-linear-regression.html#univariate-graphical-summaries"><i class="fa fa-check"></i><b>1.1.3</b> Univariate Graphical Summaries</a></li>
<li class="chapter" data-level="1.1.4" data-path="review-of-multiple-linear-regression.html"><a href="review-of-multiple-linear-regression.html#bivariate-graphical-summaries"><i class="fa fa-check"></i><b>1.1.4</b> Bivariate Graphical Summaries</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="review-of-multiple-linear-regression.html"><a href="review-of-multiple-linear-regression.html#simple-linear-regression-model"><i class="fa fa-check"></i><b>1.2</b> Simple Linear Regression Model</a><ul>
<li class="chapter" data-level="1.2.1" data-path="review-of-multiple-linear-regression.html"><a href="review-of-multiple-linear-regression.html#model-for-winning-time-and-year"><i class="fa fa-check"></i><b>1.2.1</b> Model for Winning Time and Year</a></li>
<li class="chapter" data-level="1.2.2" data-path="review-of-multiple-linear-regression.html"><a href="review-of-multiple-linear-regression.html#first-model-r-output"><i class="fa fa-check"></i><b>1.2.2</b> First Model R Output</a></li>
<li class="chapter" data-level="1.2.3" data-path="review-of-multiple-linear-regression.html"><a href="review-of-multiple-linear-regression.html#checking-model-assumptions"><i class="fa fa-check"></i><b>1.2.3</b> Checking Model Assumptions</a></li>
<li class="chapter" data-level="1.2.4" data-path="review-of-multiple-linear-regression.html"><a href="review-of-multiple-linear-regression.html#quadratic-term-for-year"><i class="fa fa-check"></i><b>1.2.4</b> Quadratic Term for Year</a></li>
<li class="chapter" data-level="1.2.5" data-path="review-of-multiple-linear-regression.html"><a href="review-of-multiple-linear-regression.html#quadratic-model-in-r"><i class="fa fa-check"></i><b>1.2.5</b> Quadratic Model in R</a></li>
<li class="chapter" data-level="1.2.6" data-path="review-of-multiple-linear-regression.html"><a href="review-of-multiple-linear-regression.html#quadratic-model-residual-plots"><i class="fa fa-check"></i><b>1.2.6</b> Quadratic Model Residual Plots</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="review-of-multiple-linear-regression.html"><a href="review-of-multiple-linear-regression.html#multiple-linear-regression-with-two-predictors"><i class="fa fa-check"></i><b>1.3</b> Multiple Linear Regression with Two Predictors</a><ul>
<li class="chapter" data-level="1.3.1" data-path="review-of-multiple-linear-regression.html"><a href="review-of-multiple-linear-regression.html#model-with-year-and-fast-track"><i class="fa fa-check"></i><b>1.3.1</b> Model with Year and Fast Track</a></li>
<li class="chapter" data-level="1.3.2" data-path="review-of-multiple-linear-regression.html"><a href="review-of-multiple-linear-regression.html#multiple-regression-model-in-r"><i class="fa fa-check"></i><b>1.3.2</b> Multiple Regression Model in R</a></li>
<li class="chapter" data-level="1.3.3" data-path="review-of-multiple-linear-regression.html"><a href="review-of-multiple-linear-regression.html#confidence-intervals-from-mlr-model"><i class="fa fa-check"></i><b>1.3.3</b> Confidence Intervals from MLR Model</a></li>
<li class="chapter" data-level="1.3.4" data-path="review-of-multiple-linear-regression.html"><a href="review-of-multiple-linear-regression.html#slopes-for-fast-non-fast-tracks"><i class="fa fa-check"></i><b>1.3.4</b> Slopes for Fast, non-Fast Tracks</a></li>
<li class="chapter" data-level="1.3.5" data-path="review-of-multiple-linear-regression.html"><a href="review-of-multiple-linear-regression.html#mlr-model-with-interaction"><i class="fa fa-check"></i><b>1.3.5</b> MLR Model with Interaction</a></li>
<li class="chapter" data-level="1.3.6" data-path="review-of-multiple-linear-regression.html"><a href="review-of-multiple-linear-regression.html#model-equations-for-fast-non-fast-tracks"><i class="fa fa-check"></i><b>1.3.6</b> Model Equations for Fast, Non-Fast Tracks</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="review-of-multiple-linear-regression.html"><a href="review-of-multiple-linear-regression.html#building-a-multiple-linear-regression-model"><i class="fa fa-check"></i><b>1.4</b> Building a Multiple Linear Regression Model</a><ul>
<li class="chapter" data-level="1.4.1" data-path="review-of-multiple-linear-regression.html"><a href="review-of-multiple-linear-regression.html#model-building-considerations"><i class="fa fa-check"></i><b>1.4.1</b> Model Building Considerations</a></li>
<li class="chapter" data-level="1.4.2" data-path="review-of-multiple-linear-regression.html"><a href="review-of-multiple-linear-regression.html#model-diagnostics"><i class="fa fa-check"></i><b>1.4.2</b> Model Diagnostics</a></li>
<li class="chapter" data-level="1.4.3" data-path="review-of-multiple-linear-regression.html"><a href="review-of-multiple-linear-regression.html#three-possible-models"><i class="fa fa-check"></i><b>1.4.3</b> Three Possible Models</a></li>
<li class="chapter" data-level="1.4.4" data-path="review-of-multiple-linear-regression.html"><a href="review-of-multiple-linear-regression.html#mlr-models-fit-in-r"><i class="fa fa-check"></i><b>1.4.4</b> MLR Models Fit in R</a></li>
<li class="chapter" data-level="1.4.5" data-path="review-of-multiple-linear-regression.html"><a href="review-of-multiple-linear-regression.html#model-0a-output"><i class="fa fa-check"></i><b>1.4.5</b> Model 0A Output</a></li>
<li class="chapter" data-level="1.4.6" data-path="review-of-multiple-linear-regression.html"><a href="review-of-multiple-linear-regression.html#model-0b-output"><i class="fa fa-check"></i><b>1.4.6</b> Model 0B Output</a></li>
<li class="chapter" data-level="1.4.7" data-path="review-of-multiple-linear-regression.html"><a href="review-of-multiple-linear-regression.html#model-0c-output"><i class="fa fa-check"></i><b>1.4.7</b> Model 0C Output</a></li>
<li class="chapter" data-level="1.4.8" data-path="review-of-multiple-linear-regression.html"><a href="review-of-multiple-linear-regression.html#goodness-of-fit-tests"><i class="fa fa-check"></i><b>1.4.8</b> Goodness of Fit Tests</a></li>
<li class="chapter" data-level="1.4.9" data-path="review-of-multiple-linear-regression.html"><a href="review-of-multiple-linear-regression.html#anova-f-statistic"><i class="fa fa-check"></i><b>1.4.9</b> ANOVA F-Statistic</a></li>
<li class="chapter" data-level="1.4.10" data-path="review-of-multiple-linear-regression.html"><a href="review-of-multiple-linear-regression.html#final-model-residual-plots"><i class="fa fa-check"></i><b>1.4.10</b> Final Model Residual Plots</a></li>
<li class="chapter" data-level="1.4.11" data-path="review-of-multiple-linear-regression.html"><a href="review-of-multiple-linear-regression.html#overall-conclusions"><i class="fa fa-check"></i><b>1.4.11</b> Overall Conclusions</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="introduction-to-correlated-data.html"><a href="introduction-to-correlated-data.html"><i class="fa fa-check"></i><b>2</b> Introduction to Correlated Data</a><ul>
<li class="chapter" data-level="2.1" data-path="introduction-to-correlated-data.html"><a href="introduction-to-correlated-data.html#introduction-to-correlated-data-1"><i class="fa fa-check"></i><b>2.1</b> Introduction to Correlated Data</a><ul>
<li class="chapter" data-level="2.1.1" data-path="introduction-to-correlated-data.html"><a href="introduction-to-correlated-data.html#weight-gain-in-mice-experiment-design-1"><i class="fa fa-check"></i><b>2.1.1</b> Weight Gain in Mice: Experiment Design #1</a></li>
<li class="chapter" data-level="2.1.2" data-path="introduction-to-correlated-data.html"><a href="introduction-to-correlated-data.html#mice-experiment-1-data"><i class="fa fa-check"></i><b>2.1.2</b> Mice Experiment 1 Data</a></li>
<li class="chapter" data-level="2.1.3" data-path="introduction-to-correlated-data.html"><a href="introduction-to-correlated-data.html#a-naive-graphical-analysis"><i class="fa fa-check"></i><b>2.1.3</b> A Naive Graphical Analysis</a></li>
<li class="chapter" data-level="2.1.4" data-path="introduction-to-correlated-data.html"><a href="introduction-to-correlated-data.html#a-more-informed-graphical-analysis"><i class="fa fa-check"></i><b>2.1.4</b> A More Informed Graphical Analysis</a></li>
<li class="chapter" data-level="2.1.5" data-path="introduction-to-correlated-data.html"><a href="introduction-to-correlated-data.html#table-of-mean-weight-by-diet-and-litter"><i class="fa fa-check"></i><b>2.1.5</b> Table of Mean Weight By Diet and Litter</a></li>
<li class="chapter" data-level="2.1.6" data-path="introduction-to-correlated-data.html"><a href="introduction-to-correlated-data.html#table-of-mean-weight-by-diet"><i class="fa fa-check"></i><b>2.1.6</b> Table of Mean Weight By Diet</a></li>
<li class="chapter" data-level="2.1.7" data-path="introduction-to-correlated-data.html"><a href="introduction-to-correlated-data.html#assessing-evidence-of-differences"><i class="fa fa-check"></i><b>2.1.7</b> Assessing Evidence of Differences</a></li>
<li class="chapter" data-level="2.1.8" data-path="introduction-to-correlated-data.html"><a href="introduction-to-correlated-data.html#an-improper-statistical-analysis"><i class="fa fa-check"></i><b>2.1.8</b> An Improper Statistical Analysis</a></li>
<li class="chapter" data-level="2.1.9" data-path="introduction-to-correlated-data.html"><a href="introduction-to-correlated-data.html#a-more-appropriate-statistical-analysis"><i class="fa fa-check"></i><b>2.1.9</b> A More Appropriate Statistical Analysis</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="introduction-to-correlated-data.html"><a href="introduction-to-correlated-data.html#llsr-model-for-mice-experiment"><i class="fa fa-check"></i><b>2.2</b> LLSR Model for Mice Experiment</a><ul>
<li class="chapter" data-level="2.2.1" data-path="introduction-to-correlated-data.html"><a href="introduction-to-correlated-data.html#model-formulation"><i class="fa fa-check"></i><b>2.2.1</b> Model Formulation</a></li>
<li class="chapter" data-level="2.2.2" data-path="introduction-to-correlated-data.html"><a href="introduction-to-correlated-data.html#model-accounting-for-correlation"><i class="fa fa-check"></i><b>2.2.2</b> Model Accounting For Correlation</a></li>
<li class="chapter" data-level="2.2.3" data-path="introduction-to-correlated-data.html"><a href="introduction-to-correlated-data.html#questions-of-interest"><i class="fa fa-check"></i><b>2.2.3</b> Questions of Interest</a></li>
<li class="chapter" data-level="2.2.4" data-path="introduction-to-correlated-data.html"><a href="introduction-to-correlated-data.html#fixed-and-random-effects"><i class="fa fa-check"></i><b>2.2.4</b> Fixed and Random Effects</a></li>
<li class="chapter" data-level="2.2.5" data-path="introduction-to-correlated-data.html"><a href="introduction-to-correlated-data.html#fitting-the-model-in-r"><i class="fa fa-check"></i><b>2.2.5</b> Fitting the Model in R</a></li>
<li class="chapter" data-level="2.2.6" data-path="introduction-to-correlated-data.html"><a href="introduction-to-correlated-data.html#why-not-fixed-effect-for-litter"><i class="fa fa-check"></i><b>2.2.6</b> Why Not Fixed Effect for Litter?</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="introduction-to-correlated-data.html"><a href="introduction-to-correlated-data.html#a-second-mice-experiment"><i class="fa fa-check"></i><b>2.3</b> A Second Mice Experiment</a><ul>
<li class="chapter" data-level="2.3.1" data-path="introduction-to-correlated-data.html"><a href="introduction-to-correlated-data.html#weight-gain-in-mice-experiment-2"><i class="fa fa-check"></i><b>2.3.1</b> Weight Gain in Mice: Experiment 2</a></li>
<li class="chapter" data-level="2.3.2" data-path="introduction-to-correlated-data.html"><a href="introduction-to-correlated-data.html#mice-experiment-2-data"><i class="fa fa-check"></i><b>2.3.2</b> Mice Experiment 2 Data</a></li>
<li class="chapter" data-level="2.3.3" data-path="introduction-to-correlated-data.html"><a href="introduction-to-correlated-data.html#a-naive-graphical-analysis-for-experiment-2"><i class="fa fa-check"></i><b>2.3.3</b> A Naive Graphical Analysis for Experiment 2</a></li>
<li class="chapter" data-level="2.3.4" data-path="introduction-to-correlated-data.html"><a href="introduction-to-correlated-data.html#a-more-informed-graphical-analysis-for-experiment-2"><i class="fa fa-check"></i><b>2.3.4</b> A More Informed Graphical Analysis for Experiment 2</a></li>
<li class="chapter" data-level="2.3.5" data-path="introduction-to-correlated-data.html"><a href="introduction-to-correlated-data.html#table-of-mean-weight-by-diet-for-experiment-2"><i class="fa fa-check"></i><b>2.3.5</b> Table of Mean Weight By Diet for Experiment 2</a></li>
<li class="chapter" data-level="2.3.6" data-path="introduction-to-correlated-data.html"><a href="introduction-to-correlated-data.html#table-comparing-litters-means-by-diet-for-experiment-2"><i class="fa fa-check"></i><b>2.3.6</b> Table Comparing Litters Means by Diet for Experiment 2</a></li>
<li class="chapter" data-level="2.3.7" data-path="introduction-to-correlated-data.html"><a href="introduction-to-correlated-data.html#an-inappropriate-model-for-the-second-design"><i class="fa fa-check"></i><b>2.3.7</b> An Inappropriate Model for the Second Design</a></li>
<li class="chapter" data-level="2.3.8" data-path="introduction-to-correlated-data.html"><a href="introduction-to-correlated-data.html#a-more-appropriate-model-for-experiment-2"><i class="fa fa-check"></i><b>2.3.8</b> A More Appropriate Model for Experiment 2</a></li>
<li class="chapter" data-level="2.3.9" data-path="introduction-to-correlated-data.html"><a href="introduction-to-correlated-data.html#model-for-litter-means"><i class="fa fa-check"></i><b>2.3.9</b> Model for Litter Means</a></li>
<li class="chapter" data-level="2.3.10" data-path="introduction-to-correlated-data.html"><a href="introduction-to-correlated-data.html#fixed-effect-for-litter-in-experiment-2"><i class="fa fa-check"></i><b>2.3.10</b> Fixed Effect for Litter in Experiment 2</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="introduction-to-correlated-data.html"><a href="introduction-to-correlated-data.html#a-multilevel-experiment"><i class="fa fa-check"></i><b>2.4</b> A Multilevel Experiment</a><ul>
<li class="chapter" data-level="2.4.1" data-path="introduction-to-correlated-data.html"><a href="introduction-to-correlated-data.html#experiment-2-illustration"><i class="fa fa-check"></i><b>2.4.1</b> Experiment 2 Illustration</a></li>
<li class="chapter" data-level="2.4.2" data-path="introduction-to-correlated-data.html"><a href="introduction-to-correlated-data.html#experiment-with-variables-assigned-at-different-levels"><i class="fa fa-check"></i><b>2.4.2</b> Experiment with Variables Assigned at Different Levels</a></li>
<li class="chapter" data-level="2.4.3" data-path="introduction-to-correlated-data.html"><a href="introduction-to-correlated-data.html#experiment-3-data"><i class="fa fa-check"></i><b>2.4.3</b> Experiment 3 Data</a></li>
<li class="chapter" data-level="2.4.4" data-path="introduction-to-correlated-data.html"><a href="introduction-to-correlated-data.html#graphical-analysis-for-experiment-3"><i class="fa fa-check"></i><b>2.4.4</b> Graphical Analysis for Experiment 3</a></li>
<li class="chapter" data-level="2.4.5" data-path="introduction-to-correlated-data.html"><a href="introduction-to-correlated-data.html#an-inappropriate-model-for-the-3rd-design"><i class="fa fa-check"></i><b>2.4.5</b> An Inappropriate Model for the 3rd Design</a></li>
<li class="chapter" data-level="2.4.6" data-path="introduction-to-correlated-data.html"><a href="introduction-to-correlated-data.html#a-more-appropriate-model-for-experiment-3"><i class="fa fa-check"></i><b>2.4.6</b> A More Appropriate Model for Experiment 3</a></li>
<li class="chapter" data-level="2.4.7" data-path="introduction-to-correlated-data.html"><a href="introduction-to-correlated-data.html#comparison-of-llsr-and-lme-models"><i class="fa fa-check"></i><b>2.4.7</b> Comparison of LLSR and LME Models</a></li>
</ul></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Stat 455: Advanced Statistical Modeling Notes</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="review-of-multiple-linear-regression" class="section level1">
<h1><span class="header-section-number">Chapter 1</span> Review of Multiple Linear Regression</h1>
<p>This chapter provides an outline of Sections 1.4-1.7 of <a href="https://bookdown.org/roback/bookdown-BeyondMLR/">Beyond Multiple Linear Regression</a> by Roback and Legler. Much of the text is either directly from the book, or lightly modified/summarized. Most of the code originates from the book's <a href="https://github.com/proback/BeyondMLR">Github repository</a>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">knitr<span class="op">::</span>opts_chunk<span class="op">$</span><span class="kw">set</span>(<span class="dt">echo =</span> <span class="ot">TRUE</span>, <span class="dt">message=</span><span class="ot">FALSE</span>, <span class="dt">warning=</span><span class="ot">FALSE</span>, <span class="dt">fig.height =</span> <span class="dv">3</span>, <span class="dt">fig.width =</span> <span class="dv">6</span>)
<span class="co"># Packages required for Chapter 1</span>
<span class="kw">library</span>(knitr) 
<span class="kw">library</span>(gridExtra)
<span class="kw">library</span>(GGally)
<span class="kw">library</span>(kableExtra)
<span class="kw">library</span>(jtools)
<span class="kw">library</span>(rsample)
<span class="kw">library</span>(broom)
<span class="kw">library</span>(tidyverse)    </code></pre></div>
<div id="exploratory-data-analysis" class="section level2">
<h2><span class="header-section-number">1.1</span> Exploratory Data Analysis</h2>
<div id="kentucky-derby-data" class="section level3">
<h3><span class="header-section-number">1.1.1</span> Kentucky Derby Data</h3>
<p>We use data from the Kentucky Derby, a 1.25 mile race run annually at Churchill Downs race track in Louisville, Kentucky.</p>
<p>Our data set <code>derbyplus.csv</code> contains data from 1896-2017, and includes the following variables:</p>
<ul>
<li><code>year</code> of the race,<br />
</li>
<li>winning horse (<code>winner</code>),<br />
</li>
<li><code>condition</code> of the track (fast, good, slow) ,<br />
</li>
<li>average <code>speed</code> (in feet per second) of the winner,<br />
</li>
<li>number of <code>starters</code> (horses who raced)</li>
</ul>
<p>We would like to use least squares linear regression techniques to model the speed of the winning horse as a function of track condition, field size, and trends over time.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">derby.df &lt;-<span class="st"> </span><span class="kw">read.csv</span>(<span class="st">&quot;https://raw.githubusercontent.com/proback/BeyondMLR/master/data/derbyplus.csv&quot;</span>)
<span class="kw">head</span>(derby.df)</code></pre></div>
<pre><code>##   year        winner condition speed starters
## 1 1896     Ben Brush      good 51.66        8
## 2 1897    Typhoon II      slow 49.81        6
## 3 1898       Plaudit      good 51.16        4
## 4 1899        Manuel      fast 50.00        5
## 5 1900 Lieut. Gibson      fast 52.28        7
## 6 1901  His Eminence      fast 51.66        5</code></pre>
</div>
<div id="some-data-wrangling" class="section level3">
<h3><span class="header-section-number">1.1.2</span> Some Data Wrangling</h3>
<p>We modify the data to create:<br />
* indicator (0-1) variables for whether the track was in fast or good condition<br />
* a factor variable (<code>fastfactor</code>) telling whether or not the track was fast<br />
* a variable giving years since 1896 (<code>yearnew</code>)</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">derby.df &lt;-<span class="st"> </span>derby.df <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>( <span class="dt">fast =</span> <span class="kw">ifelse</span>(condition<span class="op">==</span><span class="st">&quot;fast&quot;</span>,<span class="dv">1</span>,<span class="dv">0</span>), 
          <span class="dt">good =</span> <span class="kw">ifelse</span>(condition<span class="op">==</span><span class="st">&quot;good&quot;</span>,<span class="dv">1</span>,<span class="dv">0</span>),
          <span class="dt">yearnew =</span> year <span class="op">-</span><span class="st"> </span><span class="dv">1896</span>,
          <span class="dt">fastfactor =</span> <span class="kw">ifelse</span>(fast <span class="op">==</span><span class="st"> </span><span class="dv">0</span>, <span class="st">&quot;not fast&quot;</span>, <span class="st">&quot;fast&quot;</span>))
table1 &lt;-<span class="st"> </span>derby.df <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">filter</span>(<span class="kw">row_number</span>() <span class="op">&lt;</span><span class="st"> </span><span class="dv">6</span> <span class="op">|</span><span class="st"> </span><span class="kw">row_number</span>() <span class="op">&gt;</span><span class="st"> </span><span class="dv">117</span>)
<span class="kw">kable</span>(table1, <span class="dt">booktabs=</span>T,<span class="dt">caption=</span><span class="st">&quot;The first five and the last five observations from the Kentucky Derby case study.&quot;</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">kable_styling</span>(<span class="dt">latex_options =</span> <span class="st">&quot;scale_down&quot;</span>)</code></pre></div>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:unnamed-chunk-1">Table 1.1: </span>The first five and the last five observations from the Kentucky Derby case study.
</caption>
<thead>
<tr>
<th style="text-align:right;">
year
</th>
<th style="text-align:left;">
winner
</th>
<th style="text-align:left;">
condition
</th>
<th style="text-align:right;">
speed
</th>
<th style="text-align:right;">
starters
</th>
<th style="text-align:right;">
fast
</th>
<th style="text-align:right;">
good
</th>
<th style="text-align:right;">
yearnew
</th>
<th style="text-align:left;">
fastfactor
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
1896
</td>
<td style="text-align:left;">
Ben Brush
</td>
<td style="text-align:left;">
good
</td>
<td style="text-align:right;">
51.66
</td>
<td style="text-align:right;">
8
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:left;">
not fast
</td>
</tr>
<tr>
<td style="text-align:right;">
1897
</td>
<td style="text-align:left;">
Typhoon II
</td>
<td style="text-align:left;">
slow
</td>
<td style="text-align:right;">
49.81
</td>
<td style="text-align:right;">
6
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:left;">
not fast
</td>
</tr>
<tr>
<td style="text-align:right;">
1898
</td>
<td style="text-align:left;">
Plaudit
</td>
<td style="text-align:left;">
good
</td>
<td style="text-align:right;">
51.16
</td>
<td style="text-align:right;">
4
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:left;">
not fast
</td>
</tr>
<tr>
<td style="text-align:right;">
1899
</td>
<td style="text-align:left;">
Manuel
</td>
<td style="text-align:left;">
fast
</td>
<td style="text-align:right;">
50.00
</td>
<td style="text-align:right;">
5
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:left;">
fast
</td>
</tr>
<tr>
<td style="text-align:right;">
1900
</td>
<td style="text-align:left;">
Lieut. Gibson
</td>
<td style="text-align:left;">
fast
</td>
<td style="text-align:right;">
52.28
</td>
<td style="text-align:right;">
7
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
4
</td>
<td style="text-align:left;">
fast
</td>
</tr>
<tr>
<td style="text-align:right;">
2013
</td>
<td style="text-align:left;">
Orb
</td>
<td style="text-align:left;">
slow
</td>
<td style="text-align:right;">
53.71
</td>
<td style="text-align:right;">
19
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
117
</td>
<td style="text-align:left;">
not fast
</td>
</tr>
<tr>
<td style="text-align:right;">
2014
</td>
<td style="text-align:left;">
California Chrome
</td>
<td style="text-align:left;">
fast
</td>
<td style="text-align:right;">
53.37
</td>
<td style="text-align:right;">
19
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
118
</td>
<td style="text-align:left;">
fast
</td>
</tr>
<tr>
<td style="text-align:right;">
2015
</td>
<td style="text-align:left;">
American Pharoah
</td>
<td style="text-align:left;">
fast
</td>
<td style="text-align:right;">
53.65
</td>
<td style="text-align:right;">
18
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
119
</td>
<td style="text-align:left;">
fast
</td>
</tr>
<tr>
<td style="text-align:right;">
2016
</td>
<td style="text-align:left;">
Nyquist
</td>
<td style="text-align:left;">
fast
</td>
<td style="text-align:right;">
54.41
</td>
<td style="text-align:right;">
20
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
120
</td>
<td style="text-align:left;">
fast
</td>
</tr>
<tr>
<td style="text-align:right;">
2017
</td>
<td style="text-align:left;">
Always Dreaming
</td>
<td style="text-align:left;">
fast
</td>
<td style="text-align:right;">
53.40
</td>
<td style="text-align:right;">
20
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
121
</td>
<td style="text-align:left;">
fast
</td>
</tr>
</tbody>
</table>
</div>
<div id="univariate-graphical-summaries" class="section level3">
<h3><span class="header-section-number">1.1.3</span> Univariate Graphical Summaries</h3>
<p>Distributions of winning speeds and number of starters</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># EDA graphs</span>
speed_hist &lt;-<span class="st"> </span><span class="kw">ggplot</span>(<span class="dt">data =</span> derby.df, <span class="kw">aes</span>(<span class="dt">x =</span> speed)) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">geom_histogram</span>(<span class="dt">binwidth =</span> <span class="fl">0.5</span>, <span class="dt">fill =</span> <span class="st">&quot;white&quot;</span>,
                 <span class="dt">color =</span> <span class="st">&quot;black&quot;</span>) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">xlab</span>(<span class="st">&quot;Winning speed (ft/s)&quot;</span>) <span class="op">+</span><span class="st"> </span><span class="kw">ylab</span>(<span class="st">&quot;Frequency&quot;</span>) <span class="op">+</span><span class="st"> </span><span class="kw">labs</span>(<span class="dt">title=</span><span class="st">&quot;(a)&quot;</span>)
starters_hist &lt;-<span class="st"> </span><span class="kw">ggplot</span>(<span class="dt">data =</span> derby.df, <span class="kw">aes</span>(<span class="dt">x =</span> starters)) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">geom_histogram</span>(<span class="dt">binwidth =</span> <span class="dv">3</span>, <span class="dt">fill =</span> <span class="st">&quot;white&quot;</span>,
                 <span class="dt">color =</span> <span class="st">&quot;black&quot;</span>) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">xlab</span>(<span class="st">&quot;Number of starters&quot;</span>) <span class="op">+</span><span class="st"> </span><span class="kw">ylab</span>(<span class="st">&quot;Frequency&quot;</span>) <span class="op">+</span><span class="st"> </span><span class="kw">labs</span>(<span class="dt">title=</span><span class="st">&quot;(b)&quot;</span>)
<span class="kw">grid.arrange</span>(speed_hist, starters_hist, <span class="dt">ncol =</span> <span class="dv">2</span>)</code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:twohist"></span>
<img src="Stat-455-Notes_files/figure-html/twohist-1.png" alt="Histograms of key continuous variables.  Plot (a) shows winning speeds, while plot (b) shows the number of starters." width="90%" />
<p class="caption">
Figure 1.1: Histograms of key continuous variables. Plot (a) shows winning speeds, while plot (b) shows the number of starters.
</p>
</div>
</div>
<div id="bivariate-graphical-summaries" class="section level3">
<h3><span class="header-section-number">1.1.4</span> Bivariate Graphical Summaries</h3>
<p>The <code>ggpairs</code> function creates a scatterplot matrix displaying relationships between all pairs of variables.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">gg &lt;-<span class="st"> </span><span class="kw">ggpairs</span>(<span class="dt">data =</span> derby.df, 
              <span class="dt">columns =</span> <span class="kw">c</span>(<span class="st">&quot;condition&quot;</span>, <span class="st">&quot;year&quot;</span>, <span class="st">&quot;starters&quot;</span>, <span class="st">&quot;speed&quot;</span>))
gg</code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:bivariate"></span>
<img src="Stat-455-Notes_files/figure-html/bivariate-1.png" alt="Relationships between pairs of variables in the Kentucky Derby data set." width="90%" />
<p class="caption">
Figure 1.2: Relationships between pairs of variables in the Kentucky Derby data set.
</p>
</div>
<ul>
<li>We see evidence of higher speeds on fast tracks and also a tendency for recent years to have more fast conditions.</li>
</ul>
<p>We examine how winning speeds have changed over time, when the track is fast and when it is not fast.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Coded scatterplot</span>
<span class="kw">ggplot</span>(derby.df, <span class="kw">aes</span>(<span class="dt">x =</span> year, <span class="dt">y =</span> speed, <span class="dt">colour =</span> fastfactor)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_point</span>(<span class="kw">aes</span>(<span class="dt">shape =</span> fastfactor)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_smooth</span>(<span class="kw">aes</span>(<span class="dt">linetype =</span> fastfactor), <span class="dt">method =</span> lm, <span class="dt">se =</span> <span class="ot">FALSE</span>)</code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:codeds"></span>
<img src="Stat-455-Notes_files/figure-html/codeds-1.png" alt="Linear trends in winning speeds over time, presented separately for fast conditions vs. good or slow conditions." width="90%" />
<p class="caption">
Figure 1.3: Linear trends in winning speeds over time, presented separately for fast conditions vs. good or slow conditions.
</p>
</div>
<ul>
<li>It appears that winning speeds have increased more rapidly for tracks that are not fast. This suggests an interaction between year and track condition, since the relationship between speed and year appears to differ depending on whether or not the track was fast.</li>
</ul>
</div>
</div>
<div id="simple-linear-regression-model" class="section level2">
<h2><span class="header-section-number">1.2</span> Simple Linear Regression Model</h2>
<div id="model-for-winning-time-and-year" class="section level3">
<h3><span class="header-section-number">1.2.1</span> Model for Winning Time and Year</h3>
<p>We begin with a simple linear regression model for winning speed (<span class="math inline">\(Y\)</span>), using year since 1896 as the explanatory variable. This model has the form:</p>
<span class="math display">\[\begin{equation}
 Y_{i}=\beta_{0}+\beta_{1}\textrm{Yearnew}_{i}+\epsilon_{i} \quad \textrm{where} \quad \epsilon_{i}\sim \textrm{N}(0,\sigma^2).
\end{equation}\]</span>
<p>We obtain estimates of <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span>, denoted (<span class="math inline">\(\hat{\beta_0}\)</span> and <span class="math inline">\(\hat{\beta_1}\)</span>) by minimizing the sum of squared residuals <span class="math inline">\(SSR=\displaystyle\sum_{i=1}^{n}\left(Y_i- (\beta_{0}+\beta_{1}\textrm{Yearnew}_{i})\right)^2.\)</span></p>
</div>
<div id="first-model-r-output" class="section level3">
<h3><span class="header-section-number">1.2.2</span> First Model R Output</h3>
<p>We fit the model in R.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">model2 &lt;-<span class="st"> </span><span class="kw">lm</span>(speed <span class="op">~</span><span class="st"> </span>yearnew, <span class="dt">data =</span> derby.df)</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">coef</span>(<span class="kw">summary</span>(model2))</code></pre></div>
<pre><code>##                Estimate  Std. Error   t value      Pr(&gt;|t|)
## (Intercept) 51.58839264 0.162549197 317.37095 2.474501e-177
## yearnew      0.02612601 0.002322013  11.25145  1.716806e-20</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">cat</span>(<span class="st">&quot; R squared = &quot;</span>, <span class="kw">summary</span>(model2)<span class="op">$</span>r.squared, <span class="st">&quot;</span><span class="ch">\n</span><span class="st">&quot;</span>, 
    <span class="st">&quot;Residual standard error = &quot;</span>, <span class="kw">summary</span>(model2)<span class="op">$</span>sigma)</code></pre></div>
<pre><code>##  R squared =  0.5133724 
##  Residual standard error =  0.9032317</code></pre>
<p><strong>Interpretations:</strong></p>
<ul>
<li>The expected winning speed in 1896 is 51.59 ft/s.<br />
</li>
<li>Winning speed is expected to increase by 0.026 ft./s on average for each year since 1896. The low p-value provides evidence that average winning speed has increased over time.<br />
</li>
<li>51% of the total variability in winning speed is explained by the simple linear regression model with year since 1896 as the explanatory variable.<br />
</li>
<li>We estimate that the error standard deviation <span class="math inline">\(\sigma\)</span> is 0.90.</li>
</ul>
</div>
<div id="checking-model-assumptions" class="section level3">
<h3><span class="header-section-number">1.2.3</span> Checking Model Assumptions</h3>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Residual diagnostics for Model 2</span>
<span class="kw">par</span>(<span class="dt">mar=</span><span class="kw">c</span>(<span class="dv">4</span>,<span class="dv">4</span>,<span class="dv">4</span>,<span class="dv">4</span>))
<span class="kw">par</span>(<span class="dt">mfrow=</span><span class="kw">c</span>(<span class="dv">2</span>,<span class="dv">2</span>))
<span class="kw">plot</span>(model2)</code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:resid2"></span>
<img src="Stat-455-Notes_files/figure-html/resid2-1.png" alt="Residual plots for Model 2." width="90%" />
<p class="caption">
Figure 1.4: Residual plots for Model 2.
</p>
</div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">par</span>(<span class="dt">mfrow=</span><span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">1</span>))</code></pre></div>
<p>The residual plots help tell us what trends/relationships our model is missing, or leaving unexplained.</p>
<ul>
<li>The upper left plot, Residuals vs. Fitted, can be used to check the Linearity assumption. Residuals should be patternless around Y = 0; if not, there is a pattern in the data that is currently unaccounted for.<br />
</li>
<li>The upper right plot, Normal Q-Q, can be used to check the Normality assumption. Deviations from a straight line indicate that the distribution of residuals does not conform to a theoretical normal curve.</li>
<li>The lower left plot, Scale-Location, can be used to check the Equal Variance assumption. Positive or negative trends across the fitted values indicate variability that is not constant.</li>
<li>The lower right plot, Residuals vs. Leverage, can be used to check for influential points. Points with high leverage (having unusual values of the predictors) and/or high absolute residuals can have an undue influence on estimates of model parameters.</li>
</ul>
<p>There is typically no residual plot, to evaluate the Independence assumption. Evidence for lack of independence comes from knowing about the study design and methods of data collection. In this case, with a new field of horses each year, the assumption of independence is pretty reasonable.</p>
<p>In this case, the Residuals vs. Fitted plot indicates that a quadratic fit might be better than the linear fit of Model 2; other assumptions look reasonable.</p>
</div>
<div id="quadratic-term-for-year" class="section level3">
<h3><span class="header-section-number">1.2.4</span> Quadratic Term for Year</h3>
<p>Let's add a quadratic term to the model</p>
<span class="math display">\[\begin{equation*}
Y_{i}=\beta_{0}+\beta_{1}\textrm{Yearnew}_{i}+\beta_{2}\textrm{Yearnew}^2_{i}+\epsilon_{i}\quad \textrm{where}\quad \epsilon_{i}\sim \textrm{N}(0,\sigma^2).
\end{equation*}\]</span>
</div>
<div id="quadratic-model-in-r" class="section level3">
<h3><span class="header-section-number">1.2.5</span> Quadratic Model in R</h3>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">derby.df &lt;-<span class="st"> </span><span class="kw">mutate</span>(derby.df, <span class="dt">yearnew2 =</span> yearnew<span class="op">^</span><span class="dv">2</span>)
model2q &lt;-<span class="st"> </span><span class="kw">lm</span>(speed <span class="op">~</span><span class="st"> </span>yearnew <span class="op">+</span><span class="st"> </span>yearnew2, <span class="dt">data =</span> derby.df)</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">coef</span>(<span class="kw">summary</span>(model2q))</code></pre></div>
<pre><code>##                  Estimate   Std. Error    t value      Pr(&gt;|t|)
## (Intercept) 50.5874565658 2.081705e-01 243.009695 2.615174e-162
## yearnew      0.0761728163 7.950413e-03   9.580989  1.838874e-16
## yearnew2    -0.0004136099 6.358703e-05  -6.504628  1.920684e-09</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">cat</span>(<span class="st">&quot; R squared = &quot;</span>, <span class="kw">summary</span>(model2q)<span class="op">$</span>r.squared, <span class="st">&quot;</span><span class="ch">\n</span><span class="st">&quot;</span>, 
    <span class="st">&quot;Residual standard error = &quot;</span>, <span class="kw">summary</span>(model2q)<span class="op">$</span>sigma)</code></pre></div>
<pre><code>##  R squared =  0.6410103 
##  Residual standard error =  0.7790385</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Fitted models for Model 2 and Model 2Q</span>
<span class="kw">ggplot</span>(derby.df, <span class="kw">aes</span>(<span class="dt">x =</span> year, <span class="dt">y =</span> speed)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span>
<span class="st">  </span><span class="kw">stat_smooth</span>(<span class="dt">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="dt">formula =</span> y <span class="op">~</span><span class="st"> </span>x, 
              <span class="dt">se =</span> <span class="ot">FALSE</span>, <span class="dt">linetype =</span> <span class="dv">1</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">stat_smooth</span>(<span class="dt">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="dt">formula =</span> y <span class="op">~</span><span class="st"> </span>x <span class="op">+</span><span class="st"> </span><span class="kw">I</span>(x<span class="op">^</span><span class="dv">2</span>), 
              <span class="dt">se =</span> <span class="ot">FALSE</span>, <span class="dt">linetype =</span> <span class="dv">2</span>)</code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:models2and2q"></span>
<img src="Stat-455-Notes_files/figure-html/models2and2q-1.png" alt="Linear (solid) vs. quadratic (dashed) fit." width="90%" />
<p class="caption">
Figure 1.5: Linear (solid) vs. quadratic (dashed) fit.
</p>
</div>
<ul>
<li>This model suggests that the rate of increase in winning speeds is slowing down over time.<br />
</li>
<li>The low p-value on the quadratic term provides evidence that there is indeed a quadratic relationship between speed and year (as opposed to a linear one). Furthermore, the proportion of variation in winning speeds explained by the model has increased from 51.3% to 64.1%.</li>
</ul>
</div>
<div id="quadratic-model-residual-plots" class="section level3">
<h3><span class="header-section-number">1.2.6</span> Quadratic Model Residual Plots</h3>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Residual diagnostics for Model 2</span>
<span class="kw">par</span>(<span class="dt">mar=</span><span class="kw">c</span>(<span class="dv">4</span>,<span class="dv">4</span>,<span class="dv">4</span>,<span class="dv">4</span>))
<span class="kw">par</span>(<span class="dt">mfrow=</span><span class="kw">c</span>(<span class="dv">2</span>,<span class="dv">2</span>))
<span class="kw">plot</span>(model2q)</code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:resid2q"></span>
<img src="Stat-455-Notes_files/figure-html/resid2q-1.png" alt="Residual plots for Model 2Q." width="90%" />
<p class="caption">
Figure 1.6: Residual plots for Model 2Q.
</p>
</div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">par</span>(<span class="dt">mfrow=</span><span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">1</span>))</code></pre></div>
<p>The quadratic trend in the residual vs fitted plot has disappeared, as the quadratic relationship is now explained in our model.</p>
</div>
</div>
<div id="multiple-linear-regression-with-two-predictors" class="section level2">
<h2><span class="header-section-number">1.3</span> Multiple Linear Regression with Two Predictors</h2>
<div id="model-with-year-and-fast-track" class="section level3">
<h3><span class="header-section-number">1.3.1</span> Model with Year and Fast Track</h3>
<p>We add an indicator variable for whether or not the track is fast in our model.</p>
<p>Note that the text writes an indicator using the name of the 0-1 categorical variable, as opposed to the <span class="math inline">\(\text{I}_{\text{Fast}}\)</span> notation I used in STAT 255.</p>
<p><span class="math display">\[
\begin{equation}
Y_{i}=\beta_{0}+\beta_{1}\textrm{Yearnew}_{i}+\beta_{2}\textrm{Fast}_{i}+\epsilon_{i}\quad \textrm{where}\quad \epsilon_{i}\sim \textrm{N}(0,\sigma^2).
\end{equation}
\]</span></p>
</div>
<div id="multiple-regression-model-in-r" class="section level3">
<h3><span class="header-section-number">1.3.2</span> Multiple Regression Model in R</h3>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">model4 &lt;-<span class="st"> </span><span class="kw">lm</span>(speed <span class="op">~</span><span class="st"> </span>yearnew <span class="op">+</span><span class="st"> </span>fast, <span class="dt">data =</span> derby.df)</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">coef</span>(<span class="kw">summary</span>(model4))</code></pre></div>
<pre><code>##                Estimate  Std. Error    t value      Pr(&gt;|t|)
## (Intercept) 50.91782155 0.154601703 329.348388 5.360308e-178
## yearnew      0.02258276 0.001918849  11.768907  1.116763e-21
## fast         1.22684588 0.150721259   8.139833  4.393084e-13</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">cat</span>(<span class="st">&quot; R squared = &quot;</span>, <span class="kw">summary</span>(model4)<span class="op">$</span>r.squared, <span class="st">&quot;</span><span class="ch">\n</span><span class="st">&quot;</span>, 
    <span class="st">&quot;Residual standard error = &quot;</span>, <span class="kw">summary</span>(model4)<span class="op">$</span>sigma)</code></pre></div>
<pre><code>##  R squared =  0.6874141 
##  Residual standard error =  0.7269468</code></pre>
<p><strong>Interpretations:</strong></p>
<ul>
<li>winning speeds are, on average, 1.23 ft/s faster under fast conditions after accounting for time trends (i.e. assuming year is held constant). The low p-value provides evidence that winning speeds increase over time, after accounting for track condition.<br />
</li>
<li>winning speeds are expected to increase by 0.023 ft/s per year, after accounting for track condition. The low p-value provides evidence that winning speeds are faster when the track is in fast condition, after accounting for year.<br />
This yearly effect is also smaller than the 0.026 ft/s per year we estimated the previous model, that did not account for track condition. The single-variable model appears to have slightly overestimated the average increase in speed. This is probably because track conditions have also improved over time (due to improvements in track maintenence). The single variable model cannot distinguish between improvements in track conditions and improvements in speed of the horses. The multiple regression model can estimate these effects separately.<br />
</li>
<li>Based on the <span class="math inline">\(R^2\)</span> value, Model 4 explains 68.7% of the year-to-year variability in winning speeds, a noticeable increase over using either explanatory variable alone.</li>
</ul>
</div>
<div id="confidence-intervals-from-mlr-model" class="section level3">
<h3><span class="header-section-number">1.3.3</span> Confidence Intervals from MLR Model</h3>
<p><strong>Confidence Intervals for <span class="math inline">\(\beta_0, \beta_1, \beta_2\)</span>.</strong></p>
<p>Under LINE assumptions, a confidence interval for <span class="math inline">\(\beta_j\)</span> is given by <span class="math inline">\(\hat{\beta_j} \pm t_{(n-p), (1-\alpha/2)}^* \text{SE}(\beta_j)\)</span>,</p>
<p>where <span class="math inline">\(t_{(n-p), (1-\alpha/2)}^*\)</span> represents the <span class="math inline">\((1-\alpha/2)\)</span> quantile of a t-distribution with <span class="math inline">\(n-p\)</span> degrees of freedom, <span class="math inline">\(\alpha\)</span> represents the level of significance (e.g. 0.05 for a 95% CI), and <span class="math inline">\(p\)</span> represents the number of parameters <span class="math inline">\(\beta_0, \beta_1, \ldots...\)</span></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">confint</span>(model4)</code></pre></div>
<pre><code>##                   2.5 %      97.5 %
## (Intercept) 50.61169473 51.22394836
## yearnew      0.01878324  0.02638227
## fast         0.92840273  1.52528902</code></pre>
<p><strong>Interpretations:</strong></p>
<ul>
<li>We can be 95% confident that average winning speeds increase between 0.019 and 0.026 ft/s each year, after accounting for track condition.<br />
</li>
<li>We can be 95% confident that average winning speeds under fast conditions are between 0.93 and 1.53 ft/s higher than under non-fast conditions, after accounting for the effect of year.</li>
</ul>
<p>To make a prediction for a new case, such as the winning speed in 2017, we use a prediction interval:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">new.data &lt;-<span class="st"> </span><span class="kw">data.frame</span>(<span class="dt">yearnew =</span> <span class="dv">2017</span> <span class="op">-</span><span class="st"> </span><span class="dv">1896</span>, <span class="dt">fast =</span> <span class="dv">1</span>) 
<span class="kw">predict</span>(model4, <span class="dt">new =</span> new.data, <span class="dt">interval =</span> <span class="st">&quot;prediction&quot;</span>)</code></pre></div>
<pre><code>       fit     lwr      upr
1 54.87718 53.4143 56.34006</code></pre>
<ul>
<li><p>Based on our model, we can be 95% confident that the winning speed in 2017 under fast conditions will be between 53.4 and 56.3 ft/s. Note that Always Dreaming's actual winning speed (53.40) barely fit within this interval---the 2017 winning speed was a borderline outlier on the slow side.</p></li>
<li><p>If we wanted to estimate the average value of Y among all cases with the given explanatory variable values, we would use <code>interval=&quot;confidence&quot;</code>. This doesn't really make sense in this context, since there is only one winning speed each year.</p></li>
</ul>
</div>
<div id="slopes-for-fast-non-fast-tracks" class="section level3">
<h3><span class="header-section-number">1.3.4</span> Slopes for Fast, non-Fast Tracks</h3>
<p>In model4, we assume that the expected rate of change in winning speed over time is the same, regardless of whether the track is fast or not. In either case, it is given by <span class="math inline">\(\beta_1\)</span>.</p>
<p>Thus, Model 4 produces a picture that looks like this:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">equation1 &lt;-<span class="st"> </span><span class="cf">function</span>(x){<span class="kw">coef</span>(model4)[<span class="dv">2</span>]<span class="op">*</span>x<span class="op">+</span><span class="kw">coef</span>(model4)[<span class="dv">1</span>]}
equation2  &lt;-<span class="st"> </span><span class="cf">function</span>(x){<span class="kw">coef</span>(model4)[<span class="dv">2</span>]<span class="op">*</span>x<span class="op">+</span><span class="kw">coef</span>(model4)[<span class="dv">1</span>]<span class="op">+</span><span class="kw">coef</span>(model4)[<span class="dv">3</span>]}
<span class="kw">ggplot</span>(<span class="dt">data=</span>derby.df, <span class="kw">aes</span>(<span class="dt">x=</span>yearnew, <span class="dt">y=</span>speed, <span class="dt">color=</span>fastfactor)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_point</span>()<span class="op">+</span>
<span class="st">        </span><span class="kw">stat_function</span>(<span class="dt">fun=</span>equation1,<span class="dt">geom=</span><span class="st">&quot;line&quot;</span>,<span class="dt">color=</span>scales<span class="op">::</span><span class="kw">hue_pal</span>()(<span class="dv">3</span>)[<span class="dv">3</span>]) <span class="op">+</span>
<span class="st">        </span><span class="kw">stat_function</span>(<span class="dt">fun=</span>equation2,<span class="dt">geom=</span><span class="st">&quot;line&quot;</span>,<span class="dt">color=</span>scales<span class="op">::</span><span class="kw">hue_pal</span>()(<span class="dv">3</span>)[<span class="dv">1</span>]) </code></pre></div>
<p><img src="Stat-455-Notes_files/figure-html/unnamed-chunk-6-1.png" width="768" /></p>
<p>Recall, however, that the data suggested that speeds have increased more rapidly for tracks that are not fast.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Coded scatterplot</span>
<span class="kw">ggplot</span>(derby.df, <span class="kw">aes</span>(<span class="dt">x =</span> year, <span class="dt">y =</span> speed, <span class="dt">colour =</span> fastfactor)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_point</span>(<span class="kw">aes</span>(<span class="dt">shape =</span> fastfactor)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_smooth</span>(<span class="kw">aes</span>(<span class="dt">linetype =</span> fastfactor), <span class="dt">method =</span> lm, <span class="dt">se =</span> <span class="ot">FALSE</span>)</code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-7"></span>
<img src="Stat-455-Notes_files/figure-html/unnamed-chunk-7-1.png" alt="Linear trends in winning speeds over time, presented separately for fast conditions vs. good or slow conditions." width="90%" />
<p class="caption">
Figure 1.7: Linear trends in winning speeds over time, presented separately for fast conditions vs. good or slow conditions.
</p>
</div>
</div>
<div id="mlr-model-with-interaction" class="section level3">
<h3><span class="header-section-number">1.3.5</span> MLR Model with Interaction</h3>
<p>We want to build a model allows winning speeds to increase at different rates for fast tracks than for those that are not fast. (i.e. a model that includes an interaction between <code>fast</code> and <code>yearnew</code>)</p>
<p>Thus, consider Model 5:</p>
<p><span class="math display">\[
\begin{equation*}
\begin{split}
Y_{i}&amp;= \beta_{0}+\beta_{1}\textrm{Yearnew}_{i}+\beta_{2}\textrm{Fast}_{i} \\
      &amp;{}+\beta_{3}\textrm{Yearnew}_{i}\times\textrm{Fast}_{i}+\epsilon_{i}\quad \textrm{where}\quad \epsilon_{i}\sim \textrm{N}(0,\sigma^2)
\end{split}
\end{equation*}
\]</span> ### Interaction Model Estimates</p>
<p>LLSR provides the following parameter estimates:</p>
<p>We can do this using either of the following commands</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">model5 &lt;-<span class="st"> </span><span class="kw">lm</span>(speed <span class="op">~</span><span class="st"> </span>yearnew <span class="op">+</span><span class="st"> </span>fast <span class="op">+</span><span class="st"> </span>yearnew<span class="op">:</span>fast, <span class="dt">data=</span>derby.df)
model5 &lt;-<span class="st"> </span><span class="kw">lm</span>(speed <span class="op">~</span><span class="st">  </span>yearnew<span class="op">*</span>fast, <span class="dt">data=</span>derby.df)</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">coef</span>(<span class="kw">summary</span>(model5))</code></pre></div>
<pre><code>##                 Estimate  Std. Error    t value      Pr(&gt;|t|)
## (Intercept)  50.52862926 0.205072338 246.394174 6.988530e-162
## yearnew       0.03075099 0.003470967   8.859489  9.838736e-15
## fast          1.83352259 0.262174513   6.993520  1.729697e-10
## yearnew:fast -0.01149034 0.004116733  -2.791129  6.127912e-03</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">cat</span>(<span class="st">&quot; R squared = &quot;</span>, <span class="kw">summary</span>(model5)<span class="op">$</span>r.squared, <span class="st">&quot;</span><span class="ch">\n</span><span class="st">&quot;</span>, 
    <span class="st">&quot;Residual standard error = &quot;</span>, <span class="kw">summary</span>(model5)<span class="op">$</span>sigma)</code></pre></div>
<pre><code>##  R squared =  0.7067731 
##  Residual standard error =  0.7070536</code></pre>
</div>
<div id="model-equations-for-fast-non-fast-tracks" class="section level3">
<h3><span class="header-section-number">1.3.6</span> Model Equations for Fast, Non-Fast Tracks</h3>
<p>According to our model, estimated winning speeds can be found by:</p>
<p><span class="math display">\[
\begin{equation}
 \hat{Y}_{i}=50.53+0.031\textrm{Yearnew}_{i}+1.83\textrm{Fast}_{i}-0.011\textrm{Yearnew}_{i}\times\textrm{Fast}_{i}.
\end{equation}
\]</span></p>
<p><span class="math display">\[
\begin{align*}
 \textrm{Fast}=0: &amp; \\
 \hat{Y}_{i} &amp;= 50.53+0.031\textrm{Yearnew}_{i} \\
 \textrm{Fast}=1: &amp; \\
 \hat{Y}_{i} &amp;= (50.53+1.83)+(0.031-0.011)\textrm{Yearnew}_{i}
 \end{align*}
 \]</span></p>
<p><strong>Interpretations</strong></p>
<ul>
<li><span class="math inline">\(\hat{\beta}_{0} = 50.53\)</span>. The expected winning speed in 1896 under non-fast conditions was 50.53 ft/s.</li>
<li><span class="math inline">\(\hat{\beta}_{1} = 0.031\)</span>. The expected yearly increase in winning speeds under non-fast conditions is 0.031 ft/s.</li>
<li><span class="math inline">\(\hat{\beta}_{2} = 1.83\)</span>. The winning speed in 1896 was expected to be 1.83 ft/s faster under fast conditions compared to non-fast conditions.</li>
<li><span class="math inline">\(\hat{\beta}_{3} = -0.011\)</span>. The expected yearly increase in winning speeds under fast conditions is 0.020 ft/s, compared to 0.031 ft/s under non-fast conditions, a difference of 0.011 ft/s.</li>
</ul>
</div>
</div>
<div id="building-a-multiple-linear-regression-model" class="section level2">
<h2><span class="header-section-number">1.4</span> Building a Multiple Linear Regression Model</h2>
<div id="model-building-considerations" class="section level3">
<h3><span class="header-section-number">1.4.1</span> Model Building Considerations</h3>
<p>We now add additional variables, with the goal of building a final model that provides insight into relationships between winning speed and other variables.</p>
<p>There is no single correct model, but a good model will have the following characteristics:</p>
<ul>
<li>explanatory variables allow one to address primary research questions</li>
<li>explanatory variables control for important covariates</li>
<li>potential interactions have been investigated</li>
<li>variables are centered where interpretations can be enhanced (e.g. subtract 1896 from year)</li>
<li>unnecessary terms have been removed</li>
<li>LINE assumptions and the presence of influential points have both been checked using residual plots</li>
<li>the model tells a &quot;persuasive story parsimoniously&quot;</li>
</ul>
<p>Most good models should lead to similar conclusions.</p>
</div>
<div id="model-diagnostics" class="section level3">
<h3><span class="header-section-number">1.4.2</span> Model Diagnostics</h3>
<p>Several tests and measures of model performance can be used when comparing different models for model building:</p>
<ul>
<li><span class="math inline">\(R^2\)</span>. Measures the variability in the response variable explained by the model. One problem is that <span class="math inline">\(R^2\)</span> always increases with extra predictors, even if the predictors add very little information.</li>
<li>adjusted <span class="math inline">\(R^2\)</span>. Adds a penalty for model complexity to <span class="math inline">\(R^2\)</span> so that any increase in performance must outweigh the cost of additional complexity. We should ideally favor any model with higher adjusted <span class="math inline">\(R^2\)</span>, regardless of size, but the penalty for model complexity (additional terms) is fairly ad-hoc.</li>
<li>AIC (Akaike Information Criterion). Again attempts to balance model performance with model complexity, with smaller AIC levels being preferable, regardless of model size. The BIC (Bayesian Information Criterion) is similar to the AIC, but with a greater penalty for additional model terms.</li>
<li>extra sum of squares F test. This is a generalization of the t-test for individual model coefficients which can be used to perform significance tests on <strong>nested models</strong>,  where one model is a reduced version of the other.</li>
</ul>
</div>
<div id="three-possible-models" class="section level3">
<h3><span class="header-section-number">1.4.3</span> Three Possible Models</h3>
<p>We'll consider three possible final models:</p>
<p>Model A:</p>
<p><span class="math display">\[
\begin{equation}
\begin{split}
 Y_{i}&amp;=\beta_{0}+\beta_{1}\textrm{Yearnew}_{i}+\beta_{2}\textrm{Yearnew}^2_{i}+\epsilon_{i}\quad 
      \textrm{where}\quad \epsilon_{i}\sim \textrm{N}(0,\sigma^2)
\end{split}
\end{equation}
\]</span></p>
<p>Model B:</p>
<p><span class="math display">\[
\begin{equation}
\begin{split}
 Y_{i}&amp;=\beta_{0}+\beta_{1}\textrm{Yearnew}_{i}+\beta_{2}\textrm{Yearnew}^2_{i}+\beta_{3}\textrm{Fast}_{i}\\
      &amp;{}+\beta_{4}\textrm{Good}_{i}+\beta_{5}\textrm{Starters}_{i}+\epsilon_{i}\quad 
      \textrm{where}\quad \epsilon_{i}\sim \textrm{N}(0,\sigma^2)
\end{split}
\end{equation}
\]</span></p>
<p>Note that this is equivalent to including the original track condition variable in a model. In this case, slow track is treated as the <code>baseline</code> variable, since we left the indicator for slow out of the model.</p>
<p>Model C:</p>
<p><span class="math display">\[
\begin{equation}
\begin{split}
 Y_{i}&amp;=\beta_{0}+\beta_{1}\textrm{Yearnew}_{i}+\beta_{2}\textrm{Yearnew}^2_{i}+\beta_{3}\textrm{Fast}_{i}\\
      &amp;{}+\beta_{4}\textrm{Good}_{i}+\beta_{5}\textrm{Starters}_{i}  \\ 
      &amp; + \beta_6\textrm{Yearnew}_{i}\textrm{Fast}_{i}+  \beta_7\textrm{Yearnew}_{i}\textrm{Good}_{i} \\
       &amp; + \beta_8\textrm{Yearnew}^2_{i}\textrm{Fast}_{i}+  \beta_9\textrm{Yearnew}^2_{i}\textrm{Good}_{i} \\
      &amp; + \epsilon_{i}\quad 
      \textrm{where}\quad \epsilon_{i}\sim \textrm{N}(0,\sigma^2)
\end{split}
\end{equation}
\]</span></p>
</div>
<div id="mlr-models-fit-in-r" class="section level3">
<h3><span class="header-section-number">1.4.4</span> MLR Models Fit in R</h3>
<p>We fit each model in R.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">model0A &lt;-<span class="st"> </span><span class="kw">lm</span>(speed <span class="op">~</span><span class="st"> </span>yearnew <span class="op">+</span><span class="st"> </span>yearnew2 , <span class="dt">data =</span> derby.df)
model0B &lt;-<span class="st"> </span><span class="kw">lm</span>(speed <span class="op">~</span><span class="st"> </span>yearnew <span class="op">+</span><span class="st"> </span>yearnew2 <span class="op">+</span><span class="st"> </span>fast <span class="op">+</span><span class="st"> </span>good <span class="op">+</span><span class="st"> </span>starters, <span class="dt">data =</span> derby.df)
model0C &lt;-<span class="st"> </span><span class="kw">lm</span>(speed <span class="op">~</span><span class="st"> </span>yearnew <span class="op">+</span><span class="st"> </span>yearnew2 <span class="op">+</span><span class="st"> </span>fast <span class="op">+</span><span class="st"> </span>good <span class="op">+</span><span class="st"> </span>starters <span class="op">+</span><span class="st"> </span>
<span class="st">                </span>yearnew<span class="op">:</span>fast <span class="op">+</span><span class="st"> </span>yearnew<span class="op">:</span>good <span class="op">+</span><span class="st"> </span>yearnew2<span class="op">:</span>fast <span class="op">+</span><span class="st"> </span>
<span class="st">                </span>yearnew2<span class="op">:</span>good, <span class="dt">data =</span> derby.df)</code></pre></div>
</div>
<div id="model-0a-output" class="section level3">
<h3><span class="header-section-number">1.4.5</span> Model 0A Output</h3>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">coef</span>(<span class="kw">summary</span>(model0A)) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">round</span>(<span class="dv">6</span>)</code></pre></div>
<pre><code>##              Estimate Std. Error    t value Pr(&gt;|t|)
## (Intercept) 50.587457   0.208171 243.009695        0
## yearnew      0.076173   0.007950   9.580989        0
## yearnew2    -0.000414   0.000064  -6.504628        0</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">cat</span>(<span class="st">&quot; R squared = &quot;</span>, <span class="kw">summary</span>(model0A)<span class="op">$</span>r.squared, <span class="st">&quot;</span><span class="ch">\n</span><span class="st">&quot;</span>, 
    <span class="st">&quot; Adjusted R squared = &quot;</span>, <span class="kw">summary</span>(model0A)<span class="op">$</span>adj.r.squared, <span class="st">&quot;</span><span class="ch">\n</span><span class="st">&quot;</span>,
    <span class="st">&quot;Residual standard error = &quot;</span>, <span class="kw">summary</span>(model0A)<span class="op">$</span>sigma, <span class="st">&quot;</span><span class="ch">\n</span><span class="st">&quot;</span>,
<span class="st">&quot;AIC = &quot;</span>, <span class="kw">AIC</span>(model0A))</code></pre></div>
<pre><code>##  R squared =  0.6410103 
##   Adjusted R squared =  0.6349769 
##  Residual standard error =  0.7790385 
##  AIC =  290.258</code></pre>
</div>
<div id="model-0b-output" class="section level3">
<h3><span class="header-section-number">1.4.6</span> Model 0B Output</h3>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">coef</span>(<span class="kw">summary</span>(model0B))<span class="op">%&gt;%</span><span class="st"> </span><span class="kw">round</span>(<span class="dv">6</span>)</code></pre></div>
<pre><code>##              Estimate Std. Error    t value Pr(&gt;|t|)
## (Intercept) 50.020315   0.194646 256.980337 0.000000
## yearnew      0.070034   0.006130  11.423908 0.000000
## yearnew2    -0.000370   0.000046  -8.041141 0.000000
## fast         1.392666   0.130520  10.670102 0.000000
## good         0.915698   0.207677   4.409248 0.000023
## starters    -0.025284   0.013602  -1.858827 0.065586</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">cat</span>(<span class="st">&quot; R squared = &quot;</span>, <span class="kw">summary</span>(model0B)<span class="op">$</span>r.squared, <span class="st">&quot;</span><span class="ch">\n</span><span class="st">&quot;</span>, 
        <span class="st">&quot; Adjusted R squared = &quot;</span>, <span class="kw">summary</span>(model0B)<span class="op">$</span>adj.r.squared, <span class="st">&quot;</span><span class="ch">\n</span><span class="st">&quot;</span>,
    <span class="st">&quot;Residual standard error = &quot;</span>, <span class="kw">summary</span>(model0B)<span class="op">$</span>sigma,<span class="st">&quot;</span><span class="ch">\n</span><span class="st">&quot;</span>,
<span class="st">&quot;AIC = &quot;</span>, <span class="kw">AIC</span>(model0B))</code></pre></div>
<pre><code>##  R squared =  0.8266716 
##   Adjusted R squared =  0.8192006 
##  Residual standard error =  0.5482735 
##  AIC =  207.4291</code></pre>
</div>
<div id="model-0c-output" class="section level3">
<h3><span class="header-section-number">1.4.7</span> Model 0C Output</h3>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">coef</span>(<span class="kw">summary</span>(model0C))<span class="op">%&gt;%</span><span class="st"> </span><span class="kw">round</span>(<span class="dv">6</span>)</code></pre></div>
<pre><code>##                Estimate Std. Error    t value Pr(&gt;|t|)
## (Intercept)   49.703525   0.296614 167.569982 0.000000
## yearnew        0.068568   0.013167   5.207395 0.000001
## yearnew2      -0.000290   0.000102  -2.835528 0.005430
## fast           1.697589   0.337378   5.031710 0.000002
## good           1.704844   0.468469   3.639181 0.000415
## starters      -0.018592   0.013107  -1.418444 0.158838
## yearnew:fast   0.004223   0.014398   0.293292 0.769841
## yearnew:good  -0.031672   0.021548  -1.469858 0.144404
## yearnew2:fast -0.000128   0.000114  -1.124264 0.263305
## yearnew2:good  0.000249   0.000213   1.168083 0.245254</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">cat</span>(<span class="st">&quot; R squared = &quot;</span>, <span class="kw">summary</span>(model0C)<span class="op">$</span>r.squared, <span class="st">&quot;</span><span class="ch">\n</span><span class="st">&quot;</span>, 
        <span class="st">&quot; Adjusted R squared = &quot;</span>, <span class="kw">summary</span>(model0C)<span class="op">$</span>adj.r.squared, <span class="st">&quot;</span><span class="ch">\n</span><span class="st">&quot;</span>,
    <span class="st">&quot;Residual standard error = &quot;</span>, <span class="kw">summary</span>(model0C)<span class="op">$</span>sigma, <span class="st">&quot;</span><span class="ch">\n</span><span class="st">&quot;</span>,
<span class="st">&quot;AIC = &quot;</span>, <span class="kw">AIC</span>(model0C))</code></pre></div>
<pre><code>##  R squared =  0.8498007 
##   Adjusted R squared =  0.8377311 
##  Residual standard error =  0.5194172 
##  AIC =  197.9556</code></pre>
</div>
<div id="goodness-of-fit-tests" class="section level3">
<h3><span class="header-section-number">1.4.8</span> Goodness of Fit Tests</h3>
<p>When two models are nested (that is, all the terms in the smaller model also appear in the larger model) we can compare them using a goodness of fit test.</p>
<p>Reduced Model: <span class="math inline">\(\hat{y}_i = b_0 + b_1x_{i1} + b_2{x_i2} + \ldots + b_qx_{iq}\)</span></p>
<p>Full Model: <span class="math inline">\(\hat{y}_i = b_0 + b_1x_{i1} + b_2{x_i2} + \ldots + b_qx_{iq} + b_{q+1}x_{i{q+1}} \ldots + b_px_{ip}\)</span></p>
<p>p = # parameters in Full Model<br />
q = # parameters in Reduced Model<br />
n = number of observations</p>
<p>The hypothesis are:</p>
<p>Null Hypothesis: Smaller model adequately eplains variability in the response variable.<br />
Alternative Hypothesis: Larger model better explains variability in the response variable than the smaller one.</p>
</div>
<div id="anova-f-statistic" class="section level3">
<h3><span class="header-section-number">1.4.9</span> ANOVA F-Statistic</h3>
<p>We calculate an F-statistic using the formula:</p>
<p><span class="math display">\[
F = \frac{\frac{\text{SSR}_{\text{Reduced}}-\text{SSR}_{\text{Full}}}{p-q}}{\frac{\text{SSR}_{\text{Full}}}{n-(p+1)}}
\]</span></p>
<p>When the null hypothesis is true, this statistic follows an F-distribution with <span class="math inline">\(p-q\)</span> and <span class="math inline">\(n-p\)</span> degrees of freedom.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Compare model0A and model0B</span>
<span class="kw">anova</span>(model0A, model0B, <span class="dt">test =</span> <span class="st">&quot;F&quot;</span>)</code></pre></div>
<pre><code>Analysis of Variance Table

Model 1: speed ~ yearnew + yearnew2
Model 2: speed ~ yearnew + yearnew2 + fast + good + starters
  Res.Df    RSS Df Sum of Sq      F                Pr(&gt;F)    
1    119 72.221                                              
2    116 34.870  3    37.351 41.418 &lt; 0.00000000000000022 ***
---
Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>There is very strong evidence that track condition and number of starters help explain variability in winning speed.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Compare model0A and model0B</span>
<span class="kw">anova</span>(model0B, model0C, <span class="dt">test =</span> <span class="st">&quot;F&quot;</span>)</code></pre></div>
<pre><code>Analysis of Variance Table

Model 1: speed ~ yearnew + yearnew2 + fast + good + starters
Model 2: speed ~ yearnew + yearnew2 + fast + good + starters + yearnew:fast + 
    yearnew:good + yearnew2:fast + yearnew2:good
  Res.Df    RSS Df Sum of Sq      F   Pr(&gt;F)   
1    116 34.870                                
2    112 30.217  4    4.6531 4.3117 0.002784 **
---
Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>There is evidence of interaction between year and track conditions.</p>
<p>Observations:</p>
<ul>
<li><p>There is strong evidence that model B is better than model A. Accounting for condition of track and number of starters helps explain variability in winning speeds.</p></li>
<li><p>Models B and C both seem like reasonable fits. Adjusted R^2, AIC, and the F-test all favor model C over model B. Model C is, however, much harder to interpret. The p-values on any single interaction term were large, even though the model testing for significance of interactions collectively was small. When in doubt, it's better to go with the simpler model, unless there is clear reason to choose the more complex one.</p></li>
</ul>
<p><strong>It is important to consider intuition, domain area knowledge, and interpretability when choosing a model. Do not choose a model based on statistical tests alone!</strong></p>
</div>
<div id="final-model-residual-plots" class="section level3">
<h3><span class="header-section-number">1.4.10</span> Final Model Residual Plots</h3>
<p>We'll go with model B.</p>
<p>We use residual plots to check model assumptions.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Residual diagnostics for Model B</span>
<span class="kw">par</span>(<span class="dt">mar=</span><span class="kw">c</span>(<span class="dv">4</span>,<span class="dv">4</span>,<span class="dv">4</span>,<span class="dv">4</span>))
<span class="kw">par</span>(<span class="dt">mfrow=</span><span class="kw">c</span>(<span class="dv">2</span>,<span class="dv">2</span>))
<span class="kw">plot</span>(model0B)</code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-15"></span>
<img src="Stat-455-Notes_files/figure-html/unnamed-chunk-15-1.png" alt="Residual plots for Model 0B." width="90%" />
<p class="caption">
Figure 1.8: Residual plots for Model 0B.
</p>
</div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">par</span>(<span class="dt">mfrow=</span><span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">1</span>))</code></pre></div>
<p>There do not appear to be any major model violations.</p>
<p>Model B Coefficients Table:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">coef</span>(<span class="kw">summary</span>(model0B))<span class="op">%&gt;%</span><span class="st"> </span><span class="kw">round</span>(<span class="dv">6</span>)</code></pre></div>
<pre><code>##              Estimate Std. Error    t value Pr(&gt;|t|)
## (Intercept) 50.020315   0.194646 256.980337 0.000000
## yearnew      0.070034   0.006130  11.423908 0.000000
## yearnew2    -0.000370   0.000046  -8.041141 0.000000
## fast         1.392666   0.130520  10.670102 0.000000
## good         0.915698   0.207677   4.409248 0.000023
## starters    -0.025284   0.013602  -1.858827 0.065586</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">cat</span>(<span class="st">&quot; R squared = &quot;</span>, <span class="kw">summary</span>(model0B)<span class="op">$</span>r.squared, <span class="st">&quot;</span><span class="ch">\n</span><span class="st">&quot;</span>, 
        <span class="st">&quot; Adjusted R squared = &quot;</span>, <span class="kw">summary</span>(model0B)<span class="op">$</span>adj.r.squared, <span class="st">&quot;</span><span class="ch">\n</span><span class="st">&quot;</span>,
    <span class="st">&quot;Residual standard error = &quot;</span>, <span class="kw">summary</span>(model0B)<span class="op">$</span>sigma,<span class="st">&quot;</span><span class="ch">\n</span><span class="st">&quot;</span>,
<span class="st">&quot;AIC = &quot;</span>, <span class="kw">AIC</span>(model0B))</code></pre></div>
<pre><code>##  R squared =  0.8266716 
##   Adjusted R squared =  0.8192006 
##  Residual standard error =  0.5482735 
##  AIC =  207.4291</code></pre>
</div>
<div id="overall-conclusions" class="section level3">
<h3><span class="header-section-number">1.4.11</span> Overall Conclusions</h3>
<p><strong>Conclusions:</strong><br />
* The rate of increase in winning speeds is slowing over time (negative quadratic term)<br />
* The better the condition of the track, the faster the horses tend to run<br />
* larger field, with more starters, is associated with slower winning times</p>
<p>Notice this last conclusion appears contradictory to our exploratory data analysis, which showed a positive relationship between starters and speed.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">gg &lt;-<span class="st"> </span><span class="kw">ggpairs</span>(<span class="dt">data =</span> derby.df, 
              <span class="dt">columns =</span> <span class="kw">c</span>(<span class="st">&quot;condition&quot;</span>, <span class="st">&quot;year&quot;</span>, <span class="st">&quot;starters&quot;</span>, <span class="st">&quot;speed&quot;</span>))
gg</code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-17"></span>
<img src="Stat-455-Notes_files/figure-html/unnamed-chunk-17-1.png" alt="Relationships between pairs of variables in the Kentucky Derby data set." width="90%" />
<p class="caption">
Figure 1.9: Relationships between pairs of variables in the Kentucky Derby data set.
</p>
</div>
<p>This happens because over time, the number of starters in the race has increased, as have winning speeds. So, it appears that having more starters is associated with faster winning speeds, but year is acting as a <strong>confounding</strong> variable. The multiple regression model is able to separate the effect of year from that of number of starters. The model tells us that assuming year is held constant, having more starters is actually associated with a slower winning speed.</p>
<p>A situation like this, where adding a variable (such as year) to a model results in an apparent trend disappearing or reversing itself, is called <strong>Simpson's Paradox.</strong></p>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="index.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="introduction-to-correlated-data.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/STAT455-W22/stat455-w22-notes/edit/master/01-MLR.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": "https://github.com/STAT455-W22/stat455-w22-notes/blob/master/01-MLR.Rmd",
"text": null
},
"download": null,
"search": {
"engine": "lunr",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
